version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: images
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      # - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  postgres_data: