apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-camunda-animal-picture-worker-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: {{ .Release.Name }}-camunda-animal-picture-worker